import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import { ChangeEvent, FormEvent, useState } from "react";

const CreateAccount: NextPage = () => {
  const createUserMutation = api.user.createUser.useMutation();
  const [description, setDescription] = useState("");
  const [headline, setHeadline] = useState("");
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");

  const handleDescriptionChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    setDescription(e.target.value);
  };

  const handleHeadlineChange = (e: ChangeEvent<HTMLInputElement>) => {
    setHeadline(e.target.value);
  };

  const handleEmailChange = (e: ChangeEvent<HTMLInputElement>) => {
    setEmail(e.target.value);
  };

  const handleNameChange = (e: ChangeEvent<HTMLInputElement>) => {
    setName(e.target.value);
  };

  const handleSubmitUserInfo = async (e: FormEvent) => {
    e.preventDefault();
    await createUserMutation.mutateAsync({
      name,
      email,
      description,
      headline,
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-200">
        <div className="align-center flex flex-col justify-center gap-2">
          <h1>Create your account</h1>
          <form
            onSubmit={handleSubmitUserInfo}
            className="align-center flex flex-col justify-center gap-2"
          >
            <fieldset>
              <label htmlFor="user-headline">Enter your name</label>
              <input
                type="text"
                id="user-fullname"
                value={name}
                onChange={handleNameChange}
                className="bg-white p-2"
              />
              <label htmlFor="user-headline">Enter your email</label>
              <input
                type="email"
                id="user-email"
                value={email}
                onChange={handleEmailChange}
                className="bg-white p-2"
              />
            </fieldset>
            <label htmlFor="user-headline">Enter a headline</label>
            <input
              type="text"
              id="user-headline"
              value={headline}
              onChange={handleHeadlineChange}
              className="bg-white p-2"
            />
            <label htmlFor="user-description">Enter your description</label>
            <textarea
              id="user-description"
              value={description}
              onChange={handleDescriptionChange}
              className="bg-white p-2"
            />
            <button type="submit" className="bg-white p-2">
              Submit
            </button>
          </form>
        </div>
      </main>
    </>
  );
};

export default CreateAccount;
